### ISSUE TITLE
error when computing inertia for aom?

### ISSUE THREAD

**Issue by jomulder** [TilburgNetworkGroup/remstats#43]
Hi I ran the following:
```

> library(remstats)
> reff <- ~ inertia(scaling="as.is")
> aomstats1 <- aomstats(
+   edgelist = history,
+   receiver_effects = reff,
+   attributes = info,
+   memory = "full"
+ )
> head(aomstats1$statistics$receiver_stats[,,])
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]    0    0    0    0    0 0.00    0    0 0.00     0
[2,]    0    0    0    0    0 0.00    0    0 1.33     0
[3,]    0    0    0    0    0 0.00    0    0 0.00     0
[4,]    0    0    0    0    0 0.00    0    0 0.00     0
[5,]    0    0    0    0    0 0.00    0    0 0.00     0
[6,]    0    0    0    0    0 1.64    0    0 1.33     0
> head(history)
  time actor1 actor2 setting weight
1  238    105    113    work   1.33
2  317    105    109    work   1.64
3  345    115    112    work   1.82
4  627    101    115  social   1.25
5  832    113    107  social   1.67
6  842    105    109    work   2.30
```

I don't get why the inertia stats are not counts but have decimals (btw the name "as.is" is maybe not super clear name for the raw frequencies), and I don't get why for the sixth event the inertia stats are different for these two actors. Basically what I would expect that all these nonzero elements of the stats are all 1 in this 'head'. Or am I wrong?

**Comment by mlmeijerink** [comment]
Hi Joris,

The decimal numbers are due to the presence of event weights in the "history" edgelist. When remstats detects event weights, it assumes that you want to use them for computing the endogenous statistics. To simply compute the counts, you can set the weights to one. While I agree that the name "as.is" is not very informative, "counts" would also be confusing in the case where events have weights since they are not actual counts, but rather the summed event weights. Let me know if you have any suggestions.
