### ISSUE TITLE
Error in remstimate

### ISSUE THREAD

**Issue by Mbehbahani** [TilburgNetworkGroup/remstats#47]
Hi,

When I try the example of the "README" file I encounter the following error as I run  “remstimate” function to fit the model.

- Error:
Error in if (!(method %in% c("MLE", "GDADAMAX", "BSIR", "HMC"))) { : the condition has length > 1

- The code: 

install.packages("devtools")
devtools::install_github("TilburgNetworkGroup/remify")
devtools::install_github("TilburgNetworkGroup/remstats@v3.1.0")
devtools::install_github("TilburgNetworkGroup/remstimate")
library(remify)
library(remstats)
library(remstimate)
data(history)
data(info)
effects <- ~ 1 + send("extraversion", info) + inertia()
rehObject <- remify::remify(edgelist = history, model = "tie")
statsObject <- remstats(reh = rehObject, tie_effects = effects)
fit <- remstimate::remstimate(reh = rehObject, stats = statsObject,estimator = "MLE", timing = "interval")

**Comment by jupepis** [comment]
Hi @Mbehbahani , 

there is no argument `estimator`, nor `timing` inside `remstimate()`. You probably wanted to set the argument `method = "MLE"`. 
With the current version of `remstimate`, if you do not set any `method` the function returns an error because there is no default method set up yet. 

I close this issue.

_p.s. The next time, please, open the issue on the GitHub page of the corresponding package, which in this case is the `remstimate` package._


Best,
Giuseppe
